In [2]:
import numpy as np

In [6]:
mylist = [1,2,3]

In [7]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mymatrix = np.array(mylist)

In [12]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
mymatrix.shape

(3, 3)

In [15]:
mynewmatrix = np.array(mylist)

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])