# Numpy 배열 - Part 1

In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
mymatrix = np.array(mylist)

In [8]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
mymatrix.shape

(3, 3)

In [10]:
mynewmatrix = np.array(mylist)

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numpy 배열 - Part 2

In [23]:
np.random.rand(5,5)

array([[0.20788414, 0.32673073, 0.18782689, 0.90555343, 0.78468118],
       [0.45910117, 0.49883244, 0.60272557, 0.57308505, 0.97188109],
       [0.085408  , 0.33451292, 0.94244599, 0.35273893, 0.50466633],
       [0.89468516, 0.00399382, 0.03039711, 0.36153363, 0.88887858],
       [0.50529613, 0.25075708, 0.02169052, 0.77023143, 0.32213215]])

In [28]:
np.random.randn(10)

array([ 0.77643779,  0.64234505, -1.20377725,  2.27200966, -0.03018256,
        2.531874  ,  0.1094912 , -0.69164153,  0.61323603, -0.81508782])

In [29]:
np.random.normal()

-0.23881900648470206

In [42]:
np.random.randint(1,100,10)

array([98, 55, 22, 14, 91, 32, 34, 21,  1, 57])

In [50]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [51]:
arr = np.arange(25)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr = np.random.randint(0,50,10)

In [72]:
ranarr

array([48,  4,  1, 42, 41, 20, 13, 19,  3, 19])

In [62]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
ranarr.max()

48

In [67]:
ranarr.min()

1

In [70]:
ranarr.argmax()

0

In [74]:
ranarr.argmin()

2

In [77]:
ranarr.dtype

dtype('int64')

# Numpy 인덱싱과 선택

In [82]:
arr = np.arange(0,11)

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr[8]

8

In [88]:
arr[1:5]

array([1, 2, 3, 4])

In [90]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [92]:
arr[:5]

array([0, 1, 2, 3, 4])

In [94]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [97]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [98]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
slice_of_arr = arr[0:6] # slice는 arr를 reference 하고 있음

In [103]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [106]:
slice_of_arr[:] = 99

In [108]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [110]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [112]:
arr_copy = arr.copy()

In [114]:
arr_copy[:] = 10000

In [118]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [119]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [120]:
# INDEXING on 2d array

In [122]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [123]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [125]:
arr_2d.shape

(3, 3)

In [127]:
arr_2d[1]

array([20, 25, 30])

In [129]:
arr_2d[1][1]

25

In [131]:
arr_2d[1,1]

25

In [133]:
arr_2d[2,2]

45

In [143]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [145]:
# 조건부선택
arr = np.arange(1,11)

In [146]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
arr > 4 # 브로드캐스트 된다고 표현함

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [151]:
bool_arr = arr > 4

In [153]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [156]:
arr[bool_arr] # 필터 역할을함

array([ 5,  6,  7,  8,  9, 10])

In [158]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [160]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

# NumPy 연산

In [161]:
arr = np.arange(0,10)

In [162]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [164]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [168]:
1 / arr

/var/folders/7r/4n64zf2507q31h2p7fhhvb380000gn/T/ipykernel_30393/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [169]:
arr / arr

/var/folders/7r/4n64zf2507q31h2p7fhhvb380000gn/T/ipykernel_30393/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [170]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [171]:
np.log(arr)

/var/folders/7r/4n64zf2507q31h2p7fhhvb380000gn/T/ipykernel_30393/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [172]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [174]:
arr.sum()

45

In [175]:
arr.max()

9

In [178]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [179]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [180]:
arr_2d.shape

(3, 4)

In [181]:
arr_2d.sum()

78

In [182]:
arr_2d.sum(axis=0) # Sum of the values in columns

array([15, 18, 21, 24])

In [184]:
arr_2d.sum(axis=1)

array([10, 26, 42])